[tool.poetry]
name = "game"
version = "0.0.0"
description = ""
authors = ["Arwed Mett <arwed@amazon.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
